type: configured_gateway_service
gateway_service_url: >-
  https://api.apic.demo01.mea-presales.org/api/orgs/cd520d56-7efe-45e5-a3a7-b03b574ddbfe/availability-zones/01725384-f5fa-487d-a850-0cbbb4f0fbd5/gateway-services/dfab2e8c-f634-4c61-b5c8-ab578926bc60